const TOAST_LIFETIME = 4000;
const TOAST_GAP = 14;
const TOAST_VISIBLE = 3;
const TOAST_COLLAPSE_OFFSET = 16;
const TOAST_COLLAPSE_SCALE_STEP = 0.05;
const TOAST_VIEWPORT_OFFSET = 16;
const TOAST_ICON_SIZE = 20;
const TOAST_RADIUS = 18;
const TOAST_SWIPE_THRESHOLD = 45;
const TOAST_SWIPE_VELOCITY = 0.3;
const TOAST_SWIPE_AXIS_LOCK = 4;
const TOAST_SWIPE_ACTIVATE = 8;
const TOAST_SWIPE_FAIL = 16;
const TOAST_ACTION_REVEAL_WIDTH = 76;
const TOAST_ACTION_MIN_OPEN = 18;
const TOAST_ACTION_FLING_VELOCITY = 1600;

// The swipe-shaping tuning lives in toast.math.ts, next to the worklets that
// inline it — see the note at the top of that file.

export {
  TOAST_ACTION_FLING_VELOCITY,
  TOAST_ACTION_MIN_OPEN,
  TOAST_ACTION_REVEAL_WIDTH,
  TOAST_COLLAPSE_OFFSET,
  TOAST_COLLAPSE_SCALE_STEP,
  TOAST_GAP,
  TOAST_ICON_SIZE,
  TOAST_LIFETIME,
  TOAST_RADIUS,
  TOAST_SWIPE_ACTIVATE,
  TOAST_SWIPE_AXIS_LOCK,
  TOAST_SWIPE_FAIL,
  TOAST_SWIPE_THRESHOLD,
  TOAST_SWIPE_VELOCITY,
  TOAST_VIEWPORT_OFFSET,
  TOAST_VISIBLE,
};
